Update to always pass a default date

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -19,7 +19,15 @@ jobs:
       - uses: actions/checkout@v3
 
       - name: Run SDK automation
-        run: dotnet run --project build/tools/Automation/Automation.csproj ${{ inputs.releaseDate }} ${{ github.workspace }}
+        run: |
+          releaseDate=${{ inputs.releaseDate }}
+          if ! [[ "$inputDate" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]]
+          then
+            echo "release date is invalid $releaseDate. Defaulting to todays date"
+            releaseDate=`date +%F`
+          fi
+
+          dotnet run --project build/tools/Automation/Automation.csproj ${releaseDate} ${{ github.workspace }}
 
       - name: Run Generate Constants
         run: ./build/generateConstants.sh
